checkpoint_path: refer/checkpoint/regression_vemg2pose.ckpt
data:
  batch_size: 16
  dataset_path: D:/Dataset/emg2pose_dataset_mini
  num_workers: 2
  padding:
  - 0
  - 0
  val_test_window_length: 10000
  window_length: 10000
evaluation:
  metrics:
  - angle_mae
  - angle_mse
  - angular_derivatives
  - per_finger_angle_mae
  - pd_angle_mae
  - landmark_distances
  output_format: json
  save_predictions: false
model:
  decoder:
    hidden_size: 512
    in_channels: 84
    num_layers: 2
    out_channels: 40
    scale: 0.01
    type: SequentialLSTM
  network:
    conv_blocks:
    - in_channels: 16
      kernel_size: 11
      out_channels: 256
      stride: 5
    - in_channels: 256
      kernel_size: 5
      out_channels: 256
      stride: 2
    tds_stages:
    - channels: 16
      feature_width: 16
      in_channels: 256
      in_conv_kernel_width: 17
      in_conv_stride: 4
      kernel_width: 9
      num_blocks: 2
    - channels: 16
      feature_width: 16
      in_channels: 256
      in_conv_kernel_width: 9
      in_conv_stride: 2
      kernel_width: 5
      num_blocks: 2
      out_channels: 64
    type: TdsNetwork
  num_position_steps: 500
  provide_initial_pos: false
  state_condition: true
  type: VEMG2PoseWithInitialState
model_name: regression_model
training:
  learning_rate: 0.001
  loss_weights:
    fingertip_distance: 0.01
    mae: 1
